### ISSUE TITLE
Crashes at the first page

### ISSUE THREAD

**Issue by OctavianJulius** [mcthulhu/jorkens#5]
Hello, I am very interested in your application so I wanted to try it. I loaded my epub ebook and the cover page is showing fine but when I turn the page over once, it crashes. I tried multiple times with different ways to progress the book but it keeps crashing. Is this a known issue, are you able to help? thanks.

**Comment by mcthulhu** [comment]
I can try. What language is your book in? Do you have Stanza set up for lemmatization for that language? If not, that could be the problem. 

Are there any errors that show up in the terminal?  If there is a fatal error, error messages should appear there. After the book is open, can you press ctrl-shift-I to open the error console, and see if there are any messages that appear there when you turn the page?

**Comment by OctavianJulius** [comment]
My book is in German and I haven't changed the settings from the default. How do I turn the lemmatization on?
I went to the console through ctrl-shift-I and before turning the page, this is what I get:
![image](https://user-images.githubusercontent.com/60746276/100360647-2e7eee80-2fc7-11eb-82a5-2ad76bae9090.png)
I wasn't able to see the console after turning the page because the console crashed with jorkens. Thank you for your help.

**Comment by mcthulhu** [comment]
The "no tokens found" message indicates that it's not even getting to the point of lemmatization yet, though maybe that's just for the cover image, which probably doesn't have words on the page. The "failed to decode download font" is interesting. Is there any way that you could provide a copy of the epub? Or enough information that I could go get a copy myself?

**Comment by mcthulhu** [comment]
As for lemmatization, have you followed this guidance on setup? 

Users will need to have Python 38 and Stanza installed (pip install stanza), in addition to downloading the models for the languages they need (e.g. "import stanza" and then "stanza.download('es')." They will also need to place the stanza-lemmatizer.py script on the Python scripts page in the Wiki in the Jorkens/Python folder under their Documents folder. (This is only working on Windows at the moment.)

**Comment by OctavianJulius** [comment]
Okay, I haven't read the instructions then. I am currently downloading the stanza for German but where do I find the stanza-lemmatizer.py so that I can but it to the required folder?

**Comment by mcthulhu** [comment]
The Python script is on the Wiki page: https://github.com/mcthulhu/jorkens/wiki/Python-scripts-to-use-with-Jorkens.  Let's see first if installing that script and Stanza will solve your problem before we worry about the book. 

I obviously need to add some tests to check first to see whether Stanza and the script are actually present, so thank you for the reminder to do that. Jorkens should remind a user to finish that setup, and bypass lemmatization gracefully.

**Comment by OctavianJulius** [comment]
I created files in the right place and pasted the code into three files calling them by their recommended file names. Unfortunately, that doesn't work.

**Comment by mcthulhu** [comment]
OK; could you email the book to me at mcthulhu@live.com? 

Any new error messages?

**Comment by OctavianJulius** [comment]
Jorkens follows the customizations that I made on Calibri, could that play a role?

**Comment by mcthulhu** [comment]
Do you mean Calibre? No, I don't see how that could have any connection.  

Are you using Windows, and Python 3.8? Or Linux or Mac? 

In the "parsing error: invalid version" error message, was there any information around there indicating what the invalid version was of?

**Comment by OctavianJulius** [comment]
Now it doesn't give off any errors in the console when it crashes but I forgot to add in the previous messages that it gives off `DevTools failed to load SourceMap: Could not load content for file:///C:/Users/[...]/AppData/Local/Programs/jorkens/resources/app.asar/src/js/libs/fileStorage.min.js.map: `
I'm using Windows Python 3.8.6, I don't see the parsing error anymore

**Comment by OctavianJulius** [comment]
Opening the app with the CMD, this is what it gave me:
`(node:4352) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0 passages found
running stanza lemmatizer for de
Uncaught Exception: spawn C:\Python38\python.exe ENOENT`

**Comment by mcthulhu** [comment]
ENOENT means that a file can't be found. Does C:\Python38\python.exe exist on your system? Maybe you have Python installed somewhere else?

**Comment by OctavianJulius** [comment]
yup im dumb, I copied the python folder there.
It works now, thanks for your help man, and sorry about your time.
